@startuml
package com.ut5.ejerc {
  abstract class Vehiculo {
    - String matricula
    - String marca
    - String modelo
    - int anioFabricacion
    - int kilometros
    - double precio
    - Estado estado
    - Persona propietario
    + int getAnios()
    + abstract double calcularRiesgo()
    + double calcularDepreciacion()
  }
}
@enduml
